"""storytelling studio phase 1 -- Channel/Episode/Story/Chapter/Scene +
Character/Location bibles + StoryRun/StoryCheckpoint, and the additive
Series columns.

Revision ID: 0001_storytelling_studio_phase1
Revises:
Create Date: 2026-09-07

NOTE (see app/db/schema.py::sync_schema): in normal operation this
migration's upgrade() never runs -- `Base.metadata.create_all()` produces
the current schema on startup and an unversioned DB is stamped straight at
head. This file exists so `alembic downgrade base && alembic upgrade head`
cycles cleanly in dev/test, so a from-scratch contributor has an accurate
snapshot, and so every later migration has a real parent revision. It is
hand-written (not autogenerated) to keep it to exactly the Phase 1 delta
-- the real dev database has unrelated pre-Alembic drift that autogenerate
would otherwise try to "fix".
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_storytelling_studio_phase1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _ts(name: str, *, onupdate: bool = False) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), nullable=True)


def upgrade() -> None:
    op.create_table(
        "story_channel",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False, server_default="en"),
        sa.Column("locale", sa.String(), nullable=True),
        sa.Column("niche", sa.String(), nullable=True),
        sa.Column("voice_config_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("branding_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("visual_style_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("metadata_style_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("schedule_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("youtube_channel_pk", sa.Integer(), nullable=True),
        _ts("created_at"),
        _ts("updated_at"),
    )

    op.create_table(
        "episode",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="PLANNED"),
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.Column("compiled_project_ids_json", sa.JSON(), nullable=False, server_default="[]"),
        _ts("created_at"),
        _ts("updated_at"),
    )
    op.create_index("ix_episode_series_id", "episode", ["series_id"])

    op.create_table(
        "story",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("episode_id", sa.Integer(), sa.ForeignKey("episode.id"), nullable=True),
        sa.Column("mode", sa.String(), nullable=False, server_default="STORY"),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("logline", sa.Text(), nullable=True),
        sa.Column("genre", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="DRAFT"),
        sa.Column("story_bible_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("style_bible_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("project_config_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("budget_usd", sa.Float(), nullable=True),
        sa.Column("production_profile", sa.String(), nullable=False, server_default="BALANCED"),
        sa.Column("reference_notes", sa.Text(), nullable=True),
        sa.Column("content_idea_id", sa.Integer(), nullable=True),
        _ts("created_at"),
        _ts("updated_at"),
    )
    op.create_index("ix_story_episode_id", "story", ["episode_id"])
    op.create_index("ix_story_status", "story", ["status"])

    op.create_table(
        "story_character",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("story_id", sa.Integer(), sa.ForeignKey("story.id"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("age", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("appearance", sa.Text(), nullable=True),
        sa.Column("hairstyle", sa.String(), nullable=True),
        sa.Column("face", sa.Text(), nullable=True),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("wardrobe", sa.Text(), nullable=True),
        sa.Column("personality", sa.Text(), nullable=True),
        sa.Column("emotional_traits", sa.Text(), nullable=True),
        sa.Column("relationships_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("negative_constraints", sa.Text(), nullable=True),
        sa.Column("canonical_prompt_block", sa.Text(), nullable=True),
        sa.Column("reference_asset_id", sa.Integer(), nullable=True),
        sa.Column("voice_id", sa.String(), nullable=True),
        sa.Column("generation_metadata_json", sa.JSON(), nullable=False, server_default="{}"),
        _ts("created_at"),
        _ts("updated_at"),
    )
    op.create_index("ix_story_character_story_id", "story_character", ["story_id"])

    op.create_table(
        "story_location",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("story_id", sa.Integer(), sa.ForeignKey("story.id"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("lighting_default", sa.String(), nullable=True),
        sa.Column("mood", sa.String(), nullable=True),
        sa.Column("reference_asset_id", sa.Integer(), nullable=True),
        _ts("created_at"),
        _ts("updated_at"),
    )
    op.create_index("ix_story_location_story_id", "story_location", ["story_id"])

    op.create_table(
        "story_chapter",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("story_id", sa.Integer(), sa.ForeignKey("story.id"), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("retention_notes", sa.Text(), nullable=True),
        sa.Column("compiled_project_id", sa.Integer(), nullable=True),
        _ts("created_at"),
        _ts("updated_at"),
    )
    op.create_index("ix_story_chapter_story_id", "story_chapter", ["story_id"])

    op.create_table(
        "story_scene",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("chapter_id", sa.Integer(), sa.ForeignKey("story_chapter.id"), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("scene_type", sa.String(), nullable=True),
        sa.Column("narration", sa.Text(), nullable=True),
        sa.Column("dialogue_json", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("character_ids_json", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("location_id", sa.Integer(), sa.ForeignKey("story_location.id"), nullable=True),
        sa.Column("image_prompt", sa.Text(), nullable=True),
        sa.Column("video_prompt", sa.Text(), nullable=True),
        sa.Column("visual_mode", sa.String(), nullable=False, server_default="STILL_WITH_MOTION"),
        sa.Column("visual_mode_source", sa.String(), nullable=False, server_default="AUTO"),
        sa.Column("motion_preset", sa.String(), nullable=True),
        sa.Column("camera", sa.String(), nullable=True),
        sa.Column("lighting", sa.String(), nullable=True),
        sa.Column("emotion", sa.String(), nullable=True),
        sa.Column("time_of_day", sa.String(), nullable=True),
        sa.Column("continuity_notes", sa.Text(), nullable=True),
        sa.Column("duration_hint", sa.Float(), nullable=False, server_default="6.0"),
        sa.Column("importance_score", sa.Integer(), nullable=True),
        sa.Column("emotion_score", sa.Integer(), nullable=True),
        sa.Column("movement_score", sa.Integer(), nullable=True),
        sa.Column("complexity_score", sa.Integer(), nullable=True),
        sa.Column("composite_score", sa.Integer(), nullable=True),
        sa.Column("est_cost_usd", sa.Float(), nullable=True),
        sa.Column("image_asset_id", sa.Integer(), nullable=True),
        sa.Column("video_asset_id", sa.Integer(), nullable=True),
        sa.Column("reuse_asset_from_scene_id", sa.Integer(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=False, server_default=sa.false()),
        _ts("created_at"),
        _ts("updated_at"),
    )
    op.create_index("ix_story_scene_chapter_id", "story_scene", ["chapter_id"])

    op.create_table(
        "story_run",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("story_id", sa.Integer(), sa.ForeignKey("story.id"), nullable=False),
        sa.Column("scope", sa.String(), nullable=False, server_default="STORY_PLAN"),
        sa.Column("status", sa.String(), nullable=False, server_default="DRAFT"),
        sa.Column("failed_stage", sa.String(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("target_language", sa.String(), nullable=True),
        sa.Column("stage_metrics_json", sa.JSON(), nullable=True),
        sa.Column("est_cost_json", sa.JSON(), nullable=True),
        sa.Column("actual_cost_usd", sa.Float(), nullable=True),
        sa.Column("compiled_project_ids_json", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("review_reason_count", sa.Integer(), nullable=False, server_default="0"),
        _ts("created_at"),
        _ts("started_at"),
        _ts("completed_at"),
        _ts("updated_at"),
    )
    op.create_index("ix_story_run_story_id", "story_run", ["story_id"])
    op.create_index("ix_story_run_status", "story_run", ["status"])
    op.create_index("ix_story_run_updated_at", "story_run", ["updated_at"])

    op.create_table(
        "story_checkpoint",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("story_run_id", sa.Integer(), sa.ForeignKey("story_run.id"), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="PENDING"),
        sa.Column("attempt", sa.Integer(), nullable=False, server_default="1"),
        _ts("started_at"),
        _ts("completed_at"),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("checkpoint_metadata_json", sa.JSON(), nullable=True),
        _ts("created_at"),
        _ts("updated_at"),
    )
    op.create_index("ix_story_checkpoint_story_run_id", "story_checkpoint", ["story_run_id"])
    op.create_index("ix_story_checkpoint_stage", "story_checkpoint", ["stage"])

    # -- Series: additive columns (ALTER on a create_all-owned table) --
    with op.batch_alter_table("series") as batch:
        batch.add_column(sa.Column("channel_id", sa.Integer(), nullable=True))
        batch.add_column(sa.Column("narrative_identity", sa.String(), nullable=True))
        batch.add_column(sa.Column("visual_identity_json", sa.JSON(), nullable=False, server_default="{}"))
        batch.add_column(sa.Column("voice_override_json", sa.JSON(), nullable=False, server_default="{}"))
        batch.add_column(sa.Column("metadata_conventions_json", sa.JSON(), nullable=False, server_default="{}"))
    op.create_index("ix_series_channel_id", "series", ["channel_id"])


def downgrade() -> None:
    op.drop_index("ix_series_channel_id", table_name="series")
    with op.batch_alter_table("series") as batch:
        batch.drop_column("metadata_conventions_json")
        batch.drop_column("voice_override_json")
        batch.drop_column("visual_identity_json")
        batch.drop_column("narrative_identity")
        batch.drop_column("channel_id")

    for tbl in (
        "story_checkpoint", "story_run", "story_scene", "story_chapter",
        "story_location", "story_character", "story", "episode", "story_channel",
    ):
        op.drop_table(tbl)
